// Generate the key bindings page from the two keymaps.
//
// The TUI's bindings come from `mp dump-keys --json`, which prints the single
// KEYMAP of clients/tui/src/app/keymap.rs that the in-TUI help overlay (`?`)
// renders. The desktop app's bindings come from
// clients/desktop/src/keymap/catalog.ts, which maps each KEYMAP row to a GUI
// action and adds the app's own rows; this script runs that file's own
// `paletteEntries()` so the page cannot read it differently from the app.
//
//   pnpm gen:keys                            # uses `mp` on PATH
//   MP_BIN=../target/debug/mp pnpm gen:keys
//
// Writes src/data/tui-keys.json and src/content/docs/reference/keys.md.
// Commit both.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

type Binding = { key: string; action: string };
type Section = { title: string; bindings: Binding[] };
type PaletteEntry = { section: string; label: string; keys: string[]; id: string | null; badge: string | null };

const MP = process.env.MP_BIN ?? 'mp';
const here = dirname(fileURLToPath(import.meta.url));
const website = join(here, '..');
const catalogPath = join(website, '..', 'clients', 'desktop', 'src', 'keymap', 'catalog.ts');
const OUT_JSON = join(website, 'src', 'data', 'tui-keys.json');
const OUT_MD = join(website, 'src', 'content', 'docs', 'reference', 'keys.md');

const json = execFileSync(MP, ['dump-keys', '--json'], { encoding: 'utf8' });
const tui: Section[] = JSON.parse(json);
const version = execFileSync(MP, ['--version'], { encoding: 'utf8' }).trim();
writeFileSync(OUT_JSON, json.endsWith('\n') ? json : json + '\n');

// Load catalog.ts with its keymap import replaced by the KEYMAP just dumped,
// so Node's type stripping can run it without the app's bundler aliases.
const source = readFileSync(catalogPath, 'utf8');
const importLine = /^import keymap from "@\/keymap\/keymap\.json";$/m;
if (!importLine.test(source)) throw new Error(`gen-keys: ${catalogPath} no longer imports keymap.json as expected`);
const scratch = join(mkdtempSync(join(tmpdir(), 'mp-gen-keys-')), 'catalog.ts');
writeFileSync(scratch, source.replace(importLine, `const keymap = ${JSON.stringify(tui)};`));
const catalog = (await import(pathToFileURL(scratch).href)) as {
  paletteEntries: (sections: Section[]) => PaletteEntry[];
  GUI_ENTRIES: PaletteEntry[];
};

function esc(text: string): string {
  return text
    .split(/(`[^`]*`)/)
    .map((part, i) =>
      i % 2 === 1
        ? part
        : part
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/([*_|[\]\\])/g, '\\$1'),
    )
    .join('');
}

const NAMED = /^(Tab|Esc|Enter|Space|PgDn|PgUp|Home|End|Left|Right|Up|Down|\d-\d)$/;

/** One key as `<kbd>`s: a chord stays one, a letter sequence is one per key. */
function kbd(token: string): string {
  const html = (k: string) => `<kbd>${k.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/\|/g, '&#124;')}</kbd>`;
  return token
    .split(' ')
    .map((part) => {
      if (part.includes('+') || NAMED.test(part) || part.length === 1) return html(part);
      return [...part].map(html).join('');
    })
    .join(' ');
}

function keys(spec: string): string {
  const alternatives = spec === '/' ? ['/'] : spec.split(/\s*\/\s*/);
  return alternatives.map(kbd).join(' <span class="kbd-sep">/</span> ');
}

function title(t: string): string {
  return t.charAt(0) + t.slice(1).toLowerCase();
}

function rows(items: { keys: string; action: string }[]): string {
  return ['| Key | Action |', '| --- | --- |', ...items.map((r) => `| ${r.keys} | ${esc(r.action)} |`)].join('\n');
}

const parts: string[] = [];
parts.push(`---
title: Key bindings
description: Every key of the terminal UI and the desktop app, generated from their keymaps.
---

<!-- Generated by website/scripts/gen-keys.ts from \`mp dump-keys --json\` (${version}) and clients/desktop/src/keymap/catalog.ts. Do not edit by hand: run \`pnpm gen:keys\`. -->

The terminal UI and the desktop app share one keymap.
Press <kbd>?</kbd> in either to see it, or <kbd>:</kbd> to run any action by name from the command palette.
Keys come in mnemonic families: <kbd>c</kbd> compose, <kbd>t</kbd> thread and attachments, <kbd>f</kbd> find, <kbd>s</kbd> sync and settings, <kbd>g</kbd> go to.
Press a family key alone and a popup lists what can follow it.

Two letters in a row, such as <kbd>c</kbd><kbd>n</kbd>, are pressed one after the other.
\`mp dump-keys\` prints the terminal table outside the app.`);

parts.push('## Terminal UI');
parts.push(`Generated from \`mp dump-keys --json\` of ${esc(version)}.`);
for (const s of tui) {
  parts.push(`### ${title(s.title)}`);
  parts.push(rows(s.bindings.map((b) => ({ keys: keys(b.key), action: b.action }))));
}

// The desktop app: every KEYMAP row it runs, with its own key where it binds
// another, then the rows only the app has.
const entries = catalog.paletteEntries(tui);
const usable = (e: PaletteEntry) => (e.badge === null || e.badge === 'key') && e.keys.length > 0;
const bySection = new Map<string, { keys: string; action: string }[]>();
const add = (section: string, row: { keys: string; action: string }) => {
  if (!bySection.has(section)) bySection.set(section, []);
  bySection.get(section)!.push(row);
};
for (const e of entries.filter(usable)) add(e.section, { keys: e.keys.map(keys).join(' <span class="kbd-or">or</span> '), action: e.label });
const paletteOnly: PaletteEntry[] = [];
for (const e of catalog.GUI_ENTRIES) {
  if (e.keys.length === 0) paletteOnly.push(e);
  else add(e.section, { keys: e.keys.map(keys).join(' <span class="kbd-or">or</span> '), action: e.label });
}
const notYet = entries.filter((e) => e.badge !== null && e.badge !== 'key' && e.badge !== 'menu');

parts.push('## Desktop app');
parts.push(`The app takes its keys from the same keymap.
The tables below list what the app runs today, with the app's own key where it binds another.
A few keys differ: <kbd>F</kbd> fetches a server-only search hit, since <kbd>f</kbd> starts the find family, and <kbd>t</kbd><kbd>t</kbd> switches the reader between HTML and plain text, since the app has no thread view yet.
The macOS menus run the same actions, and <kbd>Cmd+,</kbd> opens Settings.`);
for (const [section, items] of bySection) {
  parts.push(`### ${title(section)}`);
  parts.push(rows(items));
}
if (paletteOnly.length) {
  parts.push('### Command palette only');
  parts.push('These actions have no key. Run them from the palette (<kbd>:</kbd> or <kbd>Ctrl+p</kbd>).');
  parts.push(paletteOnly.map((e) => `- ${esc(e.label)}`).join('\n'));
}
if (notYet.length) {
  parts.push('### Not in the desktop app yet');
  parts.push('These terminal UI actions have no desktop equivalent so far.');
  const seen = new Set<string>();
  parts.push(
    notYet
      .filter((e) => !seen.has(e.section + e.label) && seen.add(e.section + e.label))
      .map((e) => `- ${esc(title(e.section))}: ${esc(e.label)}`)
      .join('\n'),
  );
}

writeFileSync(OUT_MD, parts.join('\n\n') + '\n');
console.log(`gen-keys: wrote ${OUT_JSON} and ${OUT_MD} (${version})`);
