//! TypeScript bindings for the Tauri layer's result, argument and event types,
//! generated with ts-rs into `src/protocol/generated/gui/`.
//!
//! The types derive `ts_rs::TS` only under `cfg(test)`, so the app build never
//! compiles ts-rs. `export_bindings` rewrites the committed files (`pnpm
//! gen:types`); `generated_bindings_are_current` fails when a type changed and
//! they were not regenerated. The protocol types these embed are exported by
//! `mp-protocol`'s own test into the directory above, which the `gui/` files
//! import from.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use crate::{commands, connector, error, session};

/// Exports each listed type, and its dependencies, into `$cfg`'s directory.
macro_rules! export {
    ($cfg:expr; $($ty:ty),* $(,)?) => {{
        let mut count = 0usize;
        $(
            <$ty as TS>::export_all($cfg).expect(concat!("export ", stringify!($ty)));
            count += 1;
        )*
        count
    }};
}

/// The command a developer runs when the bindings are stale.
const REGENERATE: &str = "cd clients/desktop && pnpm gen:types";

/// The subfolder of the generated directory this crate owns.
const GUI: &str = "gui";

fn committed_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/protocol/generated")
        .join(GUI)
}

/// Writes every Tauri-layer type into `dir/gui` (and the protocol types they
/// embed into `dir`), and answers how many types were listed.
fn export_into(dir: &Path) -> usize {
    // `number` for `u64` and `i64`: `serde_json` hands them to JavaScript as
    // numbers, never as `bigint`.
    let cfg = Config::new().with_large_int("number").with_out_dir(dir);
    let cfg = &cfg;
    export!(cfg;
        commands::AccountInfo,
        commands::MailboxKind,
        commands::MailboxInfo,
        commands::MailboxListing,
        commands::MessageList,
        commands::MessageText,
        commands::Attachment,
        commands::MessageMeta,
        commands::LocalSearchParams,
        commands::LocalSearchHit,
        commands::ServerSearchParams,
        commands::OperationStarted,
        commands::CancelOutcome,
        commands::VersionInfo,
        connector::ConnectFailure,
        connector::ConnectError,
        connector::Hello,
        error::ProtocolRange,
        error::GuiError,
        session::BootstrapCause,
        session::PendingKind,
        session::InterceptSource,
        session::InterceptedUrl,
        session::ConnectionStatus,
        session::GuiEvent,
    )
}

/// The `.ts` files directly in `dir`, by name.
fn read_bindings(dir: &Path) -> BTreeMap<String, String> {
    let Ok(entries) = fs::read_dir(dir) else {
        return BTreeMap::new();
    };
    entries
        .map(|e| e.expect("read_dir entry").path())
        .filter(|p| p.is_file() && p.extension().is_some_and(|x| x == "ts"))
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            (name, fs::read_to_string(&p).expect("read binding"))
        })
        .collect()
}

/// A fresh scratch directory, unique to this process and `purpose`.
fn scratch(purpose: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "mp-desktop-ts-{purpose}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir_all(&dir).expect("create scratch dir");
    dir
}

/// Every `gui/` binding, generated fresh, with the trailing space ts-rs leaves
/// after each `{` trimmed, plus an `index.ts` that re-exports them all.
fn generate() -> BTreeMap<String, String> {
    let dir = scratch("gen");
    export_into(&dir);
    let mut bindings: BTreeMap<String, String> = read_bindings(&dir.join(GUI))
        .into_iter()
        .map(|(name, body)| {
            let mut trimmed: String = body
                .lines()
                .map(|l| l.trim_end().to_owned() + "\n")
                .collect();
            trimmed.truncate(trimmed.trim_end().len());
            trimmed.push('\n');
            (name, trimmed)
        })
        .collect();
    let index: String = std::iter::once(
        "// Generated by clients/desktop/src-tauri/src/ts_bindings.rs. Do not edit this file manually.\n"
            .to_owned(),
    )
    .chain(bindings.keys().map(|name| {
        let stem = name.trim_end_matches(".ts");
        format!("export type {{ {stem} }} from \"./{stem}\";\n")
    }))
    .collect();
    bindings.insert("index.ts".to_owned(), index);
    bindings
}

/// Rewrites the committed bindings. Ignored in a plain `cargo test` because it
/// writes into the source tree; `pnpm gen:types` runs it.
#[test]
#[ignore = "writes src/protocol/generated/gui; run it through `pnpm gen:types`"]
fn export_bindings() {
    let fresh = generate();
    let target = committed_dir();
    fs::create_dir_all(&target).expect("create generated/gui");
    for name in read_bindings(&target).keys() {
        if !fresh.contains_key(name) {
            fs::remove_file(target.join(name)).expect("remove a binding no type exports");
        }
    }
    for (name, body) in &fresh {
        fs::write(target.join(name), body).expect("write binding");
    }
}

#[test]
fn generated_bindings_are_current() {
    let fresh = generate();
    let committed = read_bindings(&committed_dir());
    let stale: Vec<&String> = fresh
        .iter()
        .filter(|(name, body)| committed.get(*name) != Some(body))
        .map(|(name, _)| name)
        .collect();
    let orphaned: Vec<&String> = committed
        .keys()
        .filter(|n| !fresh.contains_key(*n))
        .collect();
    assert!(
        stale.is_empty() && orphaned.is_empty(),
        "the TypeScript bindings in src/protocol/generated/gui are stale \
         (missing or changed: {stale:?}; no longer exported: {orphaned:?}); run `{REGENERATE}`"
    );
}

/// A type that derives `TS` and is not listed in [`export_into`] would only
/// be exported if another listed type happened to reference it.
#[test]
fn every_ts_type_is_listed() {
    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let derived: usize = fs::read_dir(&src)
        .expect("read src")
        .map(|e| e.expect("read_dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "rs"))
        .map(|p| {
            fs::read_to_string(&p)
                .expect("read source")
                .matches(concat!("derive(ts_rs", "::TS)"))
                .count()
        })
        .sum();
    let listed = export_into(&scratch("count"));
    assert_eq!(
        derived, listed,
        "{derived} types derive ts_rs::TS and {listed} are listed in export_into"
    );
    let files = generate().keys().filter(|n| *n != "index.ts").count();
    assert_eq!(files, listed, "two types share one TypeScript name");
}
