// Compute every token pair's WCAG contrast ratio in both palettes of
// src/index.css and rewrite the generated tables in docs/design-tokens.md.
//
//   pnpm contrast           rewrite the table, fail on any pair under its minimum
//   pnpm contrast --check   fail when the committed table is out of date

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { evaluate, MINIMUM, PALETTES, paletteTokens, type Row } from "../src/design/contrast.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "src/index.css"), "utf8");
const docPath = join(root, "docs/design-tokens.md");
const palettes = PALETTES.map((p) => ({ ...p, rows: evaluate(paletteTokens(css, p.name)) }));

function table(rows: Row[]): string {
  return [
    "| Foreground | Background | Hex | Ratio | Minimum | Pass | Used for |",
    "|---|---|---|---|---|---|---|",
    ...rows.map(
      (r) =>
        `| \`${r.fg}\` | \`${r.bg}\` | \`${r.fgHex}\` on \`${r.bgHex}\` | ${r.ratio.toFixed(2)}:1 | ${MINIMUM[r.need]}:1 (${r.need}) | ${r.pass ? "yes" : "NO"} | ${r.use} |`,
    ),
  ].join("\n");
}

const tables = palettes.map((p) => `### ${p.title}\n\n${table(p.rows)}`).join("\n\n");

const BEGIN = "<!-- contrast:begin (generated by `pnpm contrast`, do not edit) -->";
const END = "<!-- contrast:end -->";
const doc = readFileSync(docPath, "utf8");
const a = doc.indexOf(BEGIN);
const b = doc.indexOf(END);
if (a < 0 || b < 0) {
  console.error(`${docPath}: the contrast markers are missing`);
  process.exit(2);
}
const next = `${doc.slice(0, a + BEGIN.length)}\n${tables}\n${doc.slice(b)}`;

const failing = palettes.flatMap((p) => p.rows.filter((r) => !r.pass).map((r) => ({ ...r, palette: p.name })));
for (const r of failing) {
  console.error(`FAIL ${r.palette}: ${r.fg} on ${r.bg}: ${r.ratio.toFixed(2)}:1 < ${MINIMUM[r.need]}:1`);
}

if (process.argv.includes("--check")) {
  if (next !== doc) {
    console.error("docs/design-tokens.md is out of date; run `pnpm contrast`");
    process.exit(1);
  }
} else if (next !== doc) {
  writeFileSync(docPath, next);
  console.log(`wrote ${palettes.map((p) => `${p.rows.length} ${p.name}`).join(" and ")} pairs to docs/design-tokens.md`);
}
process.exit(failing.length > 0 ? 1 : 0);
