// Compute every token pair's WCAG contrast ratio from src/index.css and
// rewrite the generated table in docs/design-tokens.md.
//
//   pnpm contrast           rewrite the table, fail on any pair under its minimum
//   pnpm contrast --check   fail when the committed table is out of date

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { evaluate, MINIMUM, rootTokens } from "../src/design/contrast.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "src/index.css"), "utf8");
const docPath = join(root, "docs/design-tokens.md");
const rows = evaluate(rootTokens(css));

const table = [
  "| Foreground | Background | Hex | Ratio | Minimum | Pass | Used for |",
  "|---|---|---|---|---|---|---|",
  ...rows.map(
    (r) =>
      `| \`${r.fg}\` | \`${r.bg}\` | \`${r.fgHex}\` on \`${r.bgHex}\` | ${r.ratio.toFixed(2)}:1 | ${MINIMUM[r.need]}:1 (${r.need}) | ${r.pass ? "yes" : "NO"} | ${r.use} |`,
  ),
].join("\n");

const BEGIN = "<!-- contrast:begin (generated by `pnpm contrast`, do not edit) -->";
const END = "<!-- contrast:end -->";
const doc = readFileSync(docPath, "utf8");
const a = doc.indexOf(BEGIN);
const b = doc.indexOf(END);
if (a < 0 || b < 0) {
  console.error(`${docPath}: the contrast markers are missing`);
  process.exit(2);
}
const next = `${doc.slice(0, a + BEGIN.length)}\n${table}\n${doc.slice(b)}`;

const failing = rows.filter((r) => !r.pass);
for (const r of failing) {
  console.error(`FAIL ${r.fg} on ${r.bg}: ${r.ratio.toFixed(2)}:1 < ${MINIMUM[r.need]}:1`);
}

if (process.argv.includes("--check")) {
  if (next !== doc) {
    console.error("docs/design-tokens.md is out of date; run `pnpm contrast`");
    process.exit(1);
  }
} else if (next !== doc) {
  writeFileSync(docPath, next);
  console.log(`wrote ${rows.length} pairs to docs/design-tokens.md`);
}
process.exit(failing.length > 0 ? 1 : 0);
